### ISSUE TITLE
Build failed in MacOS/Linux CI

### ISSUE THREAD

**Issue by miaulightouch** [obsproject/obs-plugintemplate#80] opened 2023-07-03 11:25 UTC
### Operating System Info

Windows 10

### Other OS

MacOS, Ubuntu

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.2

### OBS Studio Log URL

not available

### Expected Behavior

It works before #76 merged.

### Current Behavior

1. cannot find `<util/config-file.h>` in macos
2. connot find `obs_view_add`, `obs_view_remove` in linux

### Steps to Reproduce

here's sample repo: https://github.com/miaulightouch/obs-test-plugin/compare/df14ecd693b4e51ff76185c65a601cad610cc08e...HEAD

**Comment by RytoEX** [comment] 2023-07-03 14:05
This looks like a duplicate of #79. The second issue is probably due to the outdated libobs package from Ubuntu.

**Comment by miaulightouch** [comment] 2023-07-10 03:58
merged latest changes, linux build fixed.

**Closed** 2023-07-15 23:17 UTC
