### ISSUE TITLE
This template installs files back into the build directory when built with ninja

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-plugintemplate#59] opened 2022-12-30 21:00 UTC
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

Installs:
```
lib/obs-plugins/obs-plugintemplate.so
share/obs/obs-plugins/obs-plugintemplate/locale/en-US.ini
/usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/lib/obs-plugins/obs-plugintemplate.so
/usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs/obs-plugins/obs-plugintemplate/data/locale/en-US.ini
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/lib/obs-plugins
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/lib
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs/obs-plugins/obs-plugintemplate/data/locale
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs/obs-plugins/obs-plugintemplate/data
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs/obs-plugins/obs-plugintemplate
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs/obs-plugins
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share/obs
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release/share
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir/Release
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build/rundir
@dir /usr/ports/multimedia/obs-plugintemplate/work/.build
@dir /usr/ports/multimedia/obs-plugintemplate/work
@dir /usr/ports/multimedia/obs-plugintemplate
@dir /usr/ports/multimedia
@dir /usr/ports
```

### Steps to Reproduce

Build with ninja backend.

**Comment by yurivict** [comment] 2022-12-30 21:04
This is possibly a cmake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/24273

**Comment by PatTheMav** [comment] 2023-10-26 16:35
Please provide steps to reproduce a build setup that shows this behaviour.

**Comment by PatTheMav** [comment] 2023-12-11 17:56
Can't reproduce on FreeBSD 13.2:

```
root@obs-jail:~/GitHub/obs-plugintemplate # cmake --install build_x86_64 --prefix ./local_install
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/GitHub/obs-plugintemplate/./local_install/lib/obs-plugins/obs-plugintemplate.so
-- Set runtime path of "./local_install/lib/obs-plugins/obs-plugintemplate.so" to ""
-- Installing: /root/GitHub/obs-plugintemplate/./local_install/share/obs/obs-plugins/obs-plugintemplate
-- Installing: /root/GitHub/obs-plugintemplate/./local_install/share/obs/obs-plugins/obs-plugintemplate/locale
-- Installing: /root/GitHub/obs-plugintemplate/./local_install/share/obs/obs-plugins/obs-plugintemplate/locale/en-US.ini
```

If this issue requires specific build steps to trigger it, we need to know about those exact steps ("Build with ninja backend." is insufficient because that does not trigger the behaviour reported in the OP).

**Comment by RytoEX** [comment] 2024-01-10 05:32
Closing as no additional information was provided and we were unable to reproduce this. This can be reopened if new steps to reproduce are provided that allow us to reproduce this issue.

**Closed by RytoEX** 2024-01-10 05:32 UTC
