### ISSUE TITLE
MacOS Build failing 

### ISSUE THREAD

**Issue by ashmanix** [obsproject/obs-plugintemplate#90] opened 2023-09-24 18:29 UTC
### Operating System Info

Other

### Other OS

GitHub Action MacOS environment

### OBS Studio Version

Git

### OBS Studio Log URL

https://github.com/ashmanix/blur-filter-obs-plugin/actions/runs/6291576827/job/17080090765

### OBS Studio Crash Log URL

https://github.com/ashmanix/blur-filter-obs-plugin/actions/runs/6291576827/job/17080090765

### Expected Behavior

The MacOS template build script should run without error producing the packaged MacOS files. 

### Current Behavior

When running the CI/CD for my plugin I get an error when running the `Build Project 🧱 / Build for macOS 🍏` script. The URL where the Package.dmg file is being downloaded downloads a file with a different hash key. I get an error saying that the hash doesn't match. Changing the hash in the `buildspec.json` file still results in an error. 

This is happening with another of my plugins (using an older version of the template) when I rerun an action that worked before. Only the MacOS build are failing (https://github.com/ashmanix/obs-plugin-countdown/actions/runs/6190232337)

### Steps to Reproduce

1. Push to the main branch
2. Watch GitHub action run to build packages

### Anything else we should know?

This has only started to happen this evening from around 5:30pm UK time Sunday 24th September.

**Comment by FiniteSingularity** [comment] 2023-09-24 18:49
@ashmanix I think this is related to the issue I opened about the packaging app now having a bad checksum: https://github.com/obsproject/obs-plugintemplate/issues/91   One potential workaround is to use the wayback machine url in place of the s.sudre.free.fr url in `.github/scripts/utils.zsh/check_packages`

**Comment by ashmanix** [comment] 2023-09-24 21:26
Thanks for the suggestion. That temp fix has done the trick for now! Thanks!

**Comment by Fenrirthviti** [comment] 2023-09-24 21:36
Even though this was opened first, #91 has more info, so closing in favor there.

**Comment by Fenrirthviti** [comment] 2023-09-24 21:36
Duplicate of #91

**Closed by Fenrirthviti** 2023-09-24 21:36 UTC
